### ISSUE TITLE
Add Waypoint 

### ISSUE THREAD

**Issue by ooade** [ooade/pimg#11]
Our implementation on ScrollToView is not cool enough, we need something a little bit powerful. We'd need to add [react-waypoint](http://brigade.github.io/react-waypoint/) as a dev-dependency and ask user to install it if needed. I'm not sure how we can pull this off easily :sweat_smile:

**Comment by codeshifu** [comment]
any reason why u want this as a dev-dependency?

**Comment by ooade** [comment]
**Eliminating Unused Code**: Because not everyone will need this feature. For example, Facebook and Twitter don't use the ScrollToView feature but Medium uses.

**Comment by ooade** [comment]
I Stumbled on the [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) as  I was surfing the net today. Matches our use cases.
