### ISSUE TITLE
Goodbye scrollToReveal, Welcome fetchOnDemand

### ISSUE THREAD

**Issue by ooade** [ooade/pimg#16]
I don't think `scrollToReveal` look lucid enough. I mean, it technically mean scroll to where the image is, then reveal. It might look like the image is already been fetched in the background and just renders once we get to the image position. `fetchOnDemand` does seem to look like what it should be or not???

### WDYT?

**Comment by ashinzekene** [comment]
`fetchOnDemand` does sound better and a little more descriptive
