### ISSUE TITLE
Size is not 20 bytes

### ISSUE THREAD

**Issue by feross** [ooade/pimg#23]
Hey there! Neat package. Just wanted to let you know that the package size seems very wrong. If it was actually 20 bytes, that would mean the code literally fits in 20 characters, as each character is one byte. This is obviously impossible.

My guess is that the bundling command errored and you actually measured the length of the error message! 😅

Here's what I get:

```bash
$ cat pimg.js | gzip | wc -c
2035
```

So, roughly 2KB.

**Comment by ooade** [comment]
Yeah. I got the package size wrongly :sweat_smile: . Thanks alot :muscle:
