### ISSUE TITLE
Deal with service workers

### ISSUE THREAD

**Issue by ooade** [ooade/pimg#24]
By default, we'll take out serving the mini image if a service worker is found, and activated. But, there will be a prop to ignore this feature

I think the one with the service worker could be checked this way:
```js
if (
   'serviceWoker' in navigator && 
    navigator.serviceWorker.controller && 
    navigator.serviceWorker.controller.state === "activated"
) {
    // do some stuff
}
```

**Comment by hiteshpr** [comment]
I can work on this.

**Comment by ooade** [comment]
Okay @hiteshpr

**Comment by ooade** [comment]
Can handle individually with workbox or with a custom service worker script.
