### ISSUE TITLE
Pre v2: Fix vulnerabilities

### ISSUE THREAD

**Issue by ooade** [ooade/pimg#26]
```sh
npm audit fix --force
```

With force applied, you might get a breaking change. It's the main reason I made this an issue because I might not have the time currently to fix it.

**Comment by cByst** [comment]
Just a heads up npm isn't reporting any vulnerabilities in master. You can probably close this unless I miss understood the issue.
![image](https://user-images.githubusercontent.com/2294736/46445910-2e686880-c747-11e8-8998-941778de250c.png)

**Comment by ooade** [comment]
Sorry. It's in examples/react

**Comment by ooade** [comment]
@haidarrifki fixed this. Thanks @cByst  :+1:
