### ISSUE TITLE
Add alt support.

### ISSUE THREAD

**Issue by RobertJGabriel** [ooade/pimg#30]
Would be super handy to have alt support for the images.

**Comment by ooade** [comment]
Alt and any other image props should work fine by default since we [pass down](https://github.com/ooade/pimg/blob/master/src/index.js#L130) every prop that's not a Pimg prop.

**Comment by ooade** [comment]
But if you still have issues, feel free to post them, and maybe add steps to reproduce. A [CodeSandBox](https://codesandbox.io) will be much more appreciated. Thanks :100:
