### ISSUE TITLE
Demo - Missing

### ISSUE THREAD

**Issue by pmochine** [ooade/pimg#39]
I don't want to be this guy. But, for me as a user who is trying to understand what this package is about and how it works, I just need a demo. 

I don't want to "lose" time just by installing it and trying it out.

Thank you :)

**Comment by ooade** [comment]
Hi, @pmochine, there's an example [folder](https://github.com/ooade/pimg/tree/v2.0.0/examples) and a [URL](https://pimg.surge.sh/) at the top of the repo that shows a production-ish example.

**Comment by pmochine** [comment]
@ooade OHH how could I missed that... Sorry about this issue!

**Comment by ooade** [comment]
Glad I was able to help :)
